src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/CaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/ListingData.java
src/main/java/uk/gov/hmcts/ecm/common/model/multiples/MultipleData.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

Replace owningOffice with managingOffice

---

src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

Update EnglandWales case type id to be consistent with Scotland

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java

Fix missing constants

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/ClaimantIndType.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/CorrespondenceScotType.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/CorrespondenceType.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/ListingData.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/types/AdhocReportType.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/types/ClaimServedType.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/types/ClaimServedTypeItem.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingstojudgments/HearingsToJudgmentsCaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingstojudgments/HearingsToJudgmentsSearchResult.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingstojudgments/HearingsToJudgmentsSubmitEvent.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/DetachDataTask.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/ccd/CaseDataTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/CaseDataBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/servicebus/UpdateCaseMsgTest.java

Merge ecm-common R5.0.18-R5.0.21

---

build.gradle

Bump spring-test to 5.3.9

---

build.gradle

Bump version to 0.0.7

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOffice.java
src/test/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOfficeTest.java

https://tools.hmcts.net/jira/browse/RET-314
Add methods to determine which region an office is in
```
[ ] Yes
[x] No
```

Add methods to determine region

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CaseDataBuilder.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClientConfig.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdSubmitEventParams.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/CreationSingleDataModel.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-314
Enable event to be called to perform case transfer same country for a case that is linked to the actual case being transferred
```
[ ] Yes
[x] No
```

Case Transfer ECC cases

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/listing/ListingData.java

https://tools.hmcts.net/jira/browse/RET-825
Fix venues list in Print Hearing Lists for Scotland cases
```
[x] Yes
[ ] No
```

Fix venues list in Print Hearing Lists for Scotland

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/CaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/JudgmentReconsiderationType.java
src/main/java/uk/gov/hmcts/ecm/common/model/listing/types/ListingType.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/casesawaitingjudgment/CaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/CreationDataTask.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/DetachDataTask.java
src/main/java/uk/gov/hmcts/ecm/common/servicebus/ServiceBusSender.java
src/test/java/uk/gov/hmcts/ecm/common/model/ccd/CaseDataTest.java
src/test/java/uk/gov/hmcts/ecm/common/servicebus/UpdateCaseMsgTest.java

https://tools.hmcts.net/jira/browse/RET-873
Merge ECM R5.0.22
```
[ ] Yes
[x] No
```

Merge ECM R5.0.22

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

[RET-828](https://tools.hmcts.net/jira/browse/RET-828)
* Removes unused constants from common library
```
[ ] Yes
[X] No
```

RET-828: remove unused constants

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-880
Enable elasticsearch date search query with no tribunal office filter
```
[ ] Yes
[x] No
```

Enable ES date search with no tribunal office

---

build.gradle

Bump version 0.0.19

---

build.gradle

Reorder dependencies

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-1436
Merge ECM R5.0.26
```
[ ] Yes
[x] No
```

Merge ECM R5.0.26

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOffice.java
src/test/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOfficeTest.java

https://tools.hmcts.net/jira/browse/RET-1042
Add method to get office required for reference data lookups
```
[ ] Yes
[x] No
```

Add method to get office required for reference data lookups

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingsbyhearingtype/HearingsByHearingTypeCaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingsbyhearingtype/HearingsByHearingTypeSearchResult.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/hearingsbyhearingtype/HearingsByHearingTypeSubmitEvent.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-1459
Merge ECM R5.0.27
```
[ ] Yes
[x] No
```

Merge ECM R5.0.27

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/claimsbyhearingvenue/ClaimsByHearingVenueCaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/claimsbyhearingvenue/ClaimsByHearingVenueSearchResult.java
src/main/java/uk/gov/hmcts/ecm/common/model/reports/claimsbyhearingvenue/ClaimsByHearingVenueSubmitEvent.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/DataModelFactory.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/PreAcceptDataTask.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/RejectDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/PreAcceptDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/PreAcceptDataTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/RejectDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/RejectDataTaskTest.java

Merge ECM R5.0.28

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-937
refactored ES queries for reports
```
[ ] Yes
[X] No
```

RET-937 - Refactored ES queries for reports

---

build.gradle

Bump et-data-model 1.0.2

---

build.gradle

Bump et-data-model to 1.0.4

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-1793
Merge ECM release R5.0.29/30
```
[ ] Yes
[x] No
```

Merge ECM R5.0.29/30

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/reports/claimsbyhearingvenue/ClaimsByHearingVenueCaseData.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/UpdateDataModel.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTaskTest.java

https://tools.hmcts.net/jira/browse/RET-1983
Merge ECM R5.0.31
```
[ ] Yes
[x] No
```

Merge ECM R5.0.31

---

build.gradle

Bump version to 0.0.38

---

build.gradle

Bump version 1.0.0 as this is now ready for R1
```
[ ] Yes
[x] No
```

Bump version to 1.0.0

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/helpers/CreateUpdatesHelper.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/Partition.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/UtilHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/ScheduleConstants.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/CaseJudgementUpdate.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/client/CaseDataBuilderTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientConfigTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java
src/test/java/uk/gov/hmcts/ecm/common/helpers/ServiceBusHelper.java
src/test/java/uk/gov/hmcts/ecm/common/helpers/UtilHelperTest.java
src/test/java/uk/gov/hmcts/ecm/common/idam/models/UserDetailsTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/PreAcceptDataTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/RejectDataTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/servicebus/UpdateCaseMsgTest.java

check style fixes and bump versions 
```
[ ] Yes
[X] No
```

checkstyle fixes and bump versions

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-1861
```
[ ] Yes
[X] No
```

version incremented

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-2207
apache-poi update
```
[ ] Yes
[X] No
```

RET-2207 - poi-ooxml update

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-2323
Added jurisdiction outcomes to constants
```
[ ] Yes
[x] No
```

RET-2323: Added jurisdiction outcomes to constants

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/client/EcmCaseDataBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

Code change to implement RET-2690 and dependencies version updates.
https://tools.hmcts.net/jira/browse/RET-2690
```
[ ] Yes
[ X ] No
```

ret-2690 implementation

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-2892
```
[ ] Yes
[ X] No
```

new hearing status added as constant

---

build.gradle

[RET](https://tools.hmcts.net/jira/browse/RET-2843)
Version number update
```
[ ] Yes
[ ] No
```

RET-2843: Bumped version number

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-2289
Add constant 'In progress'
```
[ ] Yes
[x ] No
```

RET-2289: Add constant 'In progress'

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClientConfig.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-2843
Added calls to CCD to get case access assignments and revoke case assignments
```
[ ] Yes
[ x ] No
```

Ret 2843 case access

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

Required for https://tools.hmcts.net/jira/browse/RET-2274
```
[ ] Yes
[ X] No
```

Added a constant field

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOffice.java

https://tools.hmcts.net/jira/browse/RET-2819
Added EnglandWales tribunal office emails
```
[ ] Yes
[x] No
```

RET-2819: Added EnglandWales tribunal office emails

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-2956
```
[ ] Yes
[x ] No
```

RET-2956 TRIBUNAL -> Tribunal

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

RET-3596: Add new error constant

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-3684
Status update for respondents applications
```
[ ] Yes
[X] No
```

RET-3684. Add updated state

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/CaseFlagConstants.java

https://tools.hmcts.net/jira/browse/RET-3767
Added caseflag constants
```
[ ] Yes
[x] No
```

RET-3767: Added CaseFlag constants

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-3690
Add application states
```
[ ] Yes
[x] No
```

Ret 3690 - Add application states

---

build.gradle
jitpack.yml

https://tools.hmcts.net/jira/browse/RET-3887
```
[ ] Yes
[X ] No
```

java 17 upgrade

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/launchdarkly/LaunchDarklyConfiguration.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/ecm/common/launchdarkly/FeatureToggleApiTest.java

Add launch darkly config

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/launchdarkly/FeatureToggleApi.java
src/main/java/uk/gov/hmcts/ecm/common/launchdarkly/FeatureToggleAspect.java
src/test/java/uk/gov/hmcts/ecm/common/launchdarkly/FeatureToggleApiTest.java

LaunchDarkly 6.3 to 7 changes

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CaseDataBuilder.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/test/java/uk/gov/hmcts/ecm/common/client/CaseDataBuilderTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-4140
Created GenericType initialise case creation and submit case creation methods

RET-4140 Created GenericType initialise and submit case creation methods

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java

https://tools.hmcts.net/jira/browse/RET-4236
Method return type corrected
- [x ] commit messages are meaningful and follow good commit message guidelines

Ret-4236 related changes

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-4296
Add Response required constant

RET-4296 - Add Response required constant

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClientConfig.java

added generic method for triggering events

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-4701
Added EMPLOYMENT constant
```
[] Yes
[x] No
```

RET-4701: Added EMPLOYMENT constant

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/UpdateDataModel.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTaskTest.java

https://tools.hmcts.net/jira/browse/RET-4250
Add Case Stayed option to batch update
```
[] Yes
[x] No
```

RET-4250: Add Case Stayed option to batch update

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/DataModelFactory.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/DataModelParent.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/SendNotificationDataModel.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTaskTest.java

RET-4687 - Create SendNotificationTask

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java

https://tools.hmcts.net/jira/browse/RET-4687
Add lead notification radio

RET-4687 - Add lead notification radio

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTaskTest.java

https://tools.hmcts.net/jira/browse/RET-4687
Set notification field on single

RET-4687  - Set notification field on single

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/SendNotificationDataModel.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTaskTest.java

https://tools.hmcts.net/jira/browse/RET-4711
Send notifications to all

RET-4711 - Send notifications to all

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/helpers/DocumentHelper.java

https://tools.hmcts.net/jira/browse/RET-4939
Null checks added
- [ x] commit messages are meaningful and follow good commit message guidelines

null checks added

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTaskTest.java

https://tools.hmcts.net/jira/browse/RET-4732
Set notification with multiple ref

RET-4743 - Set notification with multiple ref

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/helpers/DocumentHelper.java

https://tools.hmcts.net/jira/browse/RET-4939
Null check added before the switch that sets second level doc type.
- [ x] commit messages are meaningful and follow good commit message guidelines

required null check added

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTask.java

https://tools.hmcts.net/jira/browse/RET-4715
Add handling for notification from batch file

RET-4715 - Add handling for notification from batch file

---

build.gradle
src/test/java/uk/gov/hmcts/ecm/common/client/CaseDataBuilderTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientConfigTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java
src/test/java/uk/gov/hmcts/ecm/common/helpers/CreateUpdatesHelperTest.java
src/test/java/uk/gov/hmcts/ecm/common/helpers/UtilHelperTest.java
src/test/java/uk/gov/hmcts/ecm/common/idam/models/UserDetailsTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/helper/TribunalOfficeTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/CaseJudgementUpdateTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/SendNotificationTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTaskTest.java
src/test/java/uk/gov/hmcts/ecm/common/servicebus/ServiceBusSenderTest.java

Fix unit tests

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/NotificationSchedulePayload.java
src/main/java/uk/gov/hmcts/ecm/common/model/helper/ScheduleConstants.java
src/main/java/uk/gov/hmcts/ecm/common/model/schedule/NotificationSchedulePayloadES.java
src/main/java/uk/gov/hmcts/ecm/common/model/schedule/NotificationSchedulePayloadEvent.java
src/main/java/uk/gov/hmcts/ecm/common/model/schedule/NotificationScheduleSearchCasesResult.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-4732
Add config for notifications extract

RET-4732 - Add config for notifications extract

---

build.gradle

Rollback ecm-common

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java

https://tools.hmcts.net/jira/browse/RET-4245
Transfered case search query added
- [ x] commit messages are meaningful and follow good commit message guidelines

query to find transferred case by Id

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClientConfig.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientConfigTest.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-4678
Give legal rep access to multiple

Ret 4678 - legal rep access to multiple

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java

https://tools.hmcts.net/jira/browse/RET-4245
Reform ECM case link migration
- [ x] commit messages are meaningful and follow good commit message guidelines

case migration case reference method added

---

build.gradle
src/main/resources/postcode-office.yml

New postcodes

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java
src/main/java/uk/gov/hmcts/ecm/common/helpers/ESHelper.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/DataModelParent.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/LegalRepDataModel.java
src/test/java/uk/gov/hmcts/ecm/common/client/CcdClientTest.java

https://tools.hmcts.net/jira/browse/RET-5201
Supporting LegalRep permissions for message-handler
```
[] Yes
[x] No
```

RET-5201: Supporting LegalRep permissions for message-handler

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-5205
New option for Amend Multiple

RET-5205: New option for amend Multiple

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/DetachDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/DataDetachTaskTest.java

https://tools.hmcts.net/jira/browse/RET-5255
Update Multiple fields on Single when removed from Multiple

RET-5255: Update Single after removal from Multiple

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/datamodel/UpdateDataModel.java
src/main/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTask.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataModelBuilder.java
src/test/java/uk/gov/hmcts/ecm/common/model/servicebus/tasks/UpdateDataTaskTest.java

https://tools.hmcts.net/jira/browse/RET-5232
Added jurisdictions list
```
[] Yes
[x] No
```

RET-5232: Added jurisdictions list

---

build.gradle
src/main/resources/postcode-office.yml

https://tools.hmcts.net/jira/browse/RET-5262
Specifying postcodes to reduce incorrect automatic office assignment

Postcodes!

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/constants/JurisdictionCodesConstants.java
src/main/java/uk/gov/hmcts/ecm/common/service/JurisdictionCodesMapperService.java

https://tools.hmcts.net/jira/browse/RET-5217
Populate GRA Jurisdiction Code on submission of ET1 - ExUI

Jurisdiction Code updates

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/Constants.java

https://tools.hmcts.net/jira/browse/RET-5267
Add Vetted State

RET-5267: Add Vetted State

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/model/helper/SchedulePayload.java

https://tools.hmcts.net/jira/browse/RET-5266
Add state to schedule payload

RET-5266 - Add state to schedule payload

---

build.gradle

Bumped the version in build.gradle
Bumped the version in build.gradle

Bumped the version in build.gradle

---

build.gradle
src/main/resources/postcode-office.yml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Add in Lancaster postcodes

---

build.gradle
src/main/resources/postcode-office.yml

Update office to map to Glasgow

Update office to map to Glasgow

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-5353
-----
Update to have release 3.18.7 .
-----

Update to use et-data-model release 3.18.7

---

build.gradle

https://tools.hmcts.net/jira/browse/RET-5353
-----
Update to use the latest et-data-model which is 3.17.8
-----

Update to use et-data-model release 3.18.8

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/service/pdf/PdfService.java

Fixing font issue.
- Font's previously added to defaultResources but not actually added to the instance being used

Fix font issue

---

build.gradle
src/main/java/uk/gov/hmcts/ecm/common/client/CcdClient.java

See [RET-247](https://tools.hmcts.net/jira/browse/RET-247)
Add new methods to start event for an ECM case

Add new methods to start event for an ECM case

---

build.gradle

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Fix Version

---

build.gradle
src/test/resources/requests/et3CaseData.json

https://tools.hmcts.net/jira/browse/RET-6022
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

RET-6022 - field added for ECC reply
